import { NextPage } from "next";
import Head from "next/head";
import Layout from "@/components/layout";
import Link from "next/link";
import { Formik, Form } from "formik";
import { signUpValidationSchema } from "@/validator/auth";
import Input from "@/components/ui/input";

const SignUp: NextPage = () => {
  return (
    <Layout withTopBar title="Create New Account">
      <Head>
        <title>mechat-app</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="flex-1 w-full px-[27px]">
        <Formik
          initialValues={{
            name: "",
            email: "",
            password: "",
          }}
          validationSchema={signUpValidationSchema}
          onSubmit={(values) => console.log(values)}
        >
          {({ errors }) => (
            <Form>
              <Input
                label="Name"
                type="text"
                error={errors.name}
                placeholder="Enter Your Name"
              />
              <Input
                label="Email"
                type="email"
                error={errors.email}
                placeholder="Enter Your Email"
              />
              <Input
                type="password"
                error={errors.password}
                label="Password"
                placeholder="Enter Your Password"
                isPasswordInput
              />
              <button
                type="submit"
                className="bg-brand-blue-500 rounded-[10px] w-full py-[19px] text-brand-xl leading-brand-xl font-bold text-white
          "
              >
                Sign In
              </button>
            </Form>
          )}
        </Formik>
        <p className="text-brand-blue-500 text-base font-semibold text-center mt-3">
          Have an account ?{" "}
          <Link href="/sign-in" className="font-bold">
            Sign in
          </Link>
        </p>
      </div>
    </Layout>
  );
};

export default SignUp;
