"use client";

import { NextPage } from "next";
import Head from "next/head";
import Layout from "@/components/layout";
import Link from "next/link";
import { Formik, Form } from "formik";
import { signInValidationSchema } from "@/validator/auth";
import Input from "@/components/ui/input";

const SignIn: NextPage = () => {
  const handleSubmit = (values: { email: string; password: string }) => {
    console.log(values);
  };

  return (
    <Layout withTopBar title="Welcome">
      <Head>
        <title>mechat-app</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="flex-1 w-full px-[27px]">
        <h3 className="text-brand-2xl leading-brand-2xl font-bold">Sign In</h3>
        <p className="text-lg leading-[18px mt-[25px]">
          Korem ipsum dolor sit amet, consectetur adipiscing elit.
        </p>
        <Formik
          initialValues={{
            email: "",
            password: "",
          }}
          validationSchema={signInValidationSchema}
          onSubmit={(values) => handleSubmit(values)}
        >
          {({ errors }) => (
            <Form className="mt-[62px]">
              <Input
                label="Email"
                type="email"
                error={errors.email}
                placeholder="Enter Your Email"
              />
              <Input
                type="password"
                error={errors.password}
                label="Password"
                placeholder="Enter Your Password"
                isPasswordInput
              />
              <button
                type="submit"
                className="bg-brand-blue-500 rounded-[10px] w-full py-[19px] text-brand-xl leading-brand-xl font-bold text-white
          "
              >
                Sign In
              </button>
            </Form>
          )}
        </Formik>
        <p className="text-brand-blue-500 text-base font-semibold text-center mt-3">
          Don&apos;t have account ?{" "}
          <Link href="/sign-up" className="font-bold">
            Sign Up
          </Link>
        </p>
      </div>
    </Layout>
  );
};

export default SignIn;
